package admin

import (
	"embed"
	"fmt"
	"io/fs"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/iannil/huan/internal/config"
)

//go:embed dist/*
var adminDist embed.FS

// HandlerOptions configures the admin handler. Per ADR 0011, the token is
// mandatory — loopback binds auto-generate one (printed to stderr by the
// caller via ResolveToken); non-loopback binds must set HUAN_ADMIN_TOKEN
// (enforced by CheckBindSafety before this struct is built).
type HandlerOptions struct {
	Cfg        *config.Config
	SourceDir  string
	Rebuild    func()
	ServeURL   string
	BindAddr   string // informational; used for nothing currently but kept for future allow-listing
	Token      string // required; gates all /admin/api/* requests (L2)
	MemoryDir  string // optional; if empty, audit log is disabled
}

// NewHandler creates an http.Handler for the admin panel (SPA + API).
// It serves the embedded React app on /admin/ and provides /admin/api/*
// JSON endpoints. API endpoints are wrapped in TokenMiddleware (L2);
// write operations are recorded via AuditLogger to memoryDir/daily-{date}.md (L4).
//
// Callers MUST run CheckBindSafety(bindAddr, token) BEFORE constructing
// the handler to enforce L1 (fail-fast on non-loopback bind without token).
func NewHandler(opts HandlerOptions) http.Handler {
	mux := http.NewServeMux()

	// API routes — gated by L2 token middleware.
	contentDir := filepath.Join(opts.SourceDir, "content")
	staticDir := filepath.Join(opts.SourceDir, "static")
	api := newAPIHandler(apiHandlerConfig{
		contentDir: contentDir,
		staticDir:  staticDir,
		sourceDir:  opts.SourceDir,
		rebuild:    opts.Rebuild,
		siteTitle:  opts.Cfg.Title,
		baseURL:    opts.Cfg.BaseURL,
		serveURL:   opts.ServeURL,
		audit:      NewAuditLogger(opts.MemoryDir),
	})
	apiWithAuth := TokenMiddleware(api, opts.Token)
	mux.Handle("/admin/api/", apiWithAuth)

	// Static SPA files from embedded dist/ — intentionally NOT gated by
	// token: the SPA must load to prompt for the token. The SPA serves no
	// sensitive data itself; all sensitive data flows through /admin/api/*.
	subFS, err := fs.Sub(adminDist, "dist")
	if err != nil {
		mux.Handle("/admin/", servePlaceholder())
		return mux
	}
	staticFS := http.FileServer(http.FS(subFS))
	strippedFS := http.StripPrefix("/admin/", staticFS)

	mux.HandleFunc("/admin/", func(w http.ResponseWriter, r *http.Request) {
		cleanPath := strings.TrimPrefix(r.URL.Path, "/admin/")

		// SPA fallback: paths without a file extension → serve index.html
		if !hasFileExtension(cleanPath) || cleanPath == "" {
			serveIndex(subFS, w, r)
			return
		}

		// Static files (js, css, etc.) — strip prefix and serve from embedded FS
		strippedFS.ServeHTTP(w, r)
	})

	return mux
}

// MustPrintAutoGeneratedToken prints the token to stderr exactly once when
// auto-generated (loopback case). Caller passes autoGenerated=true from
// ResolveToken(). This is informational — losing it just means the user
// must restart to see it again; they can always set HUAN_ADMIN_TOKEN
// explicitly to make it deterministic.
func MustPrintAutoGeneratedToken(token string, autoGenerated bool) {
	if !autoGenerated {
		return
	}
	fmt.Fprintf(os.Stderr,
		"\nhuan: admin panel token (save this; will not be shown again):\n    %s\n\n"+
			"To make this deterministic across restarts, set %s env.\n\n",
		token, AdminTokenEnvVar)
}

func serveIndex(subFS fs.FS, w http.ResponseWriter, r *http.Request) {
	data, err := fs.ReadFile(subFS, "index.html")
	if err != nil {
		http.Error(w, "admin UI not built (run: cd web/admin && npm run build)", http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Write(data)
}

func hasFileExtension(p string) bool {
	ext := path.Ext(p)
	return ext != "" && ext != "/"
}

func servePlaceholder() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>huan admin</title></head><body>
<h1>huan admin</h1>
<p>Admin UI not built. Run:</p>
<pre><code>cd web/admin && npm install && npm run build
cd .. && go build -o huan ./cmd/huan</code></pre>
</body></html>`))
	}
}
