package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sync/atomic"
	"time"

	"github.com/iannil/huan/internal/admin"
	"github.com/iannil/huan/internal/build"
	"github.com/iannil/huan/internal/config"
	"github.com/iannil/huan/internal/dev"
	"github.com/iannil/huan/internal/theme"
	"github.com/spf13/cobra"
)

var devCmd = &cobra.Command{
	Use:   "dev",
	Short: "Start the development server",
	Long:  "Start the development server with LiveReload, file watching, and admin panel.",
	RunE:  runDev,
}

func init() {
	rootCmd.AddCommand(devCmd)
	devCmd.Flags().String("port", "1313", "port to serve on")
	devCmd.Flags().String("bind", "127.0.0.1", "interface to bind")
	devCmd.Flags().BoolP("buildDrafts", "D", false, "include draft content")
	devCmd.Flags().Bool("disableLiveReload", false, "disable browser auto-refresh")
	devCmd.Flags().Duration("debounce", 400*time.Millisecond, "file change debounce delay")
	devCmd.Flags().Bool("disableWatch", false, "do not watch files for changes")
	devCmd.Flags().String("adminDev", "", "admin UI Vite dev server URL (e.g. http://localhost:5173) for hot reload")
	devCmd.Flags().String("plugins", "", "path to plugins directory (overrides sourceDir/plugins/)")
}

func runDev(cmd *cobra.Command, args []string) error {
	port, _ := cmd.Flags().GetString("port")
	bind, _ := cmd.Flags().GetString("bind")
	disableLR, _ := cmd.Flags().GetBool("disableLiveReload")
	disableWatch, _ := cmd.Flags().GetBool("disableWatch")
	debounce, _ := cmd.Flags().GetDuration("debounce")
	includeDrafts, _ := cmd.Flags().GetBool("buildDrafts")
	adminDevURL, _ := cmd.Flags().GetString("adminDev")
	pluginsDir, _ := cmd.Flags().GetString("plugins")

	cfg, err := config.Load(sourceDir)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}

	token, tokenFromEnv := admin.ResolveToken()
	if err := admin.CheckBindSafety(bind, token); err != nil {
		return err
	}
	if !tokenFromEnv {
		var err error
		if token, err = admin.GenerateToken(); err != nil {
			return fmt.Errorf("generate admin token: %w", err)
		}
		admin.MustPrintAutoGeneratedToken(token, true)
	}

	browserHost := bind
	if bind == "0.0.0.0" || bind == "::" {
		browserHost = "localhost"
	}

	devBaseURL := "http://" + browserHost + ":" + port + "/"
	lrURL := ""
	injectLR := false
	if !disableLR {
		injectLR = true
		lrURL = "ws://" + browserHost + ":" + port + "/livereload"
	}

	var hub *dev.LiveReloadHub
	if !disableLR {
		hub = dev.NewHub()
	}

	tmpDir, err := os.MkdirTemp("", "huan-dev-*")
	if err != nil {
		return fmt.Errorf("mkdtemp: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	buildOpts := build.Options{
		SourceDir:        sourceDir,
		OutputDir:        tmpDir,
		IncludeDrafts:    includeDrafts,
		InjectLiveReload: injectLR,
		LiveReloadURL:    lrURL,
		BaseURLOverride:  devBaseURL,
		Logf:             func(format string, a ...any) { fmt.Printf(format, a...) },
	}

	// Create PluginRegistry and ThemeManager, auto-activate from config
	reg, _ := newPluginRegistry(cfg, sourceDir, pluginsDir)
	buildOpts.PluginRegistry = reg
	themeMgr := theme.NewManager(reg)
	if cfg.Theme != "" {
		if err := themeMgr.Activate(cfg.Theme); err != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "huan: theme activate %q: %v\n", cfg.Theme, err)
		}
	}
	buildOpts.ThemeManager = themeMgr

	runBuild := func(opts build.Options) error {
		if cfg.IsMultiLanguage() {
			res, err := build.BuildMultiSite(opts)
			if err != nil {
				return err
			}
			fmt.Println(build.SummarizeMultiSite(res))
		} else {
			_, err := build.BuildSite(opts)
			if err != nil {
				return err
			}
		}
		// Run image pipeline after build if configured
		reg, _ := newPluginRegistry(cfg, sourceDir, pluginsDir)
		if err := runImagePipeline(sourceDir, opts.OutputDir, reg); err != nil {
			return fmt.Errorf("image pipeline: %w", err)
		}
		return nil
	}

	if err := runBuild(buildOpts); err != nil {
		return err
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	var (
		rebuildBusy   atomic.Bool
		rebuildPended atomic.Bool
	)
	nextDir := tmpDir + ".next"
	doRebuild := func() {
		if !rebuildBusy.CompareAndSwap(false, true) {
			rebuildPended.Store(true)
			return
		}
		for {
			fmt.Println("[watch] change detected, rebuilding...")
			start := time.Now()
			_ = os.RemoveAll(nextDir)
			buildOpts.OutputDir = nextDir
			if err := runBuild(buildOpts); err != nil {
				_ = os.RemoveAll(nextDir)
				buildOpts.OutputDir = tmpDir
				fmt.Printf("[watch] rebuild error: %v\n", err)
				if hub != nil {
					hub.BroadcastAlert(fmt.Sprintf("huan rebuild error: %v", err))
				}
				break
			}
			if err := build.SwapBuildDir(tmpDir, nextDir); err != nil {
				_ = os.RemoveAll(nextDir)
				buildOpts.OutputDir = tmpDir
				fmt.Printf("[watch] swap failed, kept old build: %v\n", err)
			}
			buildOpts.OutputDir = tmpDir
			fmt.Printf("[watch] rebuild complete in %v\n", time.Since(start))
			if hub != nil {
				hub.BroadcastReload()
			}
			if !rebuildPended.CompareAndSwap(true, false) {
				break
			}
		}
		rebuildBusy.Store(false)
	}

	if !disableWatch {
		watcher, err := dev.NewWatcher(dev.WatcherOptions{
			SourceDir: sourceDir,
			Debounce:  debounce,
			OnChange:  doRebuild,
		})
		if err != nil {
			fmt.Printf("WARNING: file watcher unavailable: %v\n", err)
			fmt.Println("WARNING: use --disableWatch to suppress this message")
		} else {
			go watcher.Run(ctx)
		}
	}

	fmt.Println("Press Ctrl+C to stop")

	serveURL := fmt.Sprintf("http://%s:%s/", browserHost, port)
	adminHandler := admin.NewHandler(admin.HandlerOptions{
		Cfg:       cfg,
		SourceDir: sourceDir,
		Rebuild:   doRebuild,
		ServeURL:  serveURL,
		BindAddr:  bind,
		Token:     token,
		MemoryDir: filepath.Join(sourceDir, "memory", "daily"),
	})
	if adminDevURL != "" {
		fmt.Printf("Admin UI dev mode: proxying to %s\n", adminDevURL)
		adminHandler = dev.NewAdminDevProxy(adminDevURL, adminHandler)
	}

	srv := dev.New(dev.ServerOptions{
		OutputDir:    tmpDir,
		Bind:         bind,
		Port:         port,
		Hub:          hub,
		AdminHandler: adminHandler,
		Logf:         func(format string, a ...any) { fmt.Printf(format, a...) },
	})
	return srv.Run(ctx)
}