package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sync/atomic"
	"time"

	"github.com/iannil/huan/internal/admin"
	"github.com/iannil/huan/internal/build"
	"github.com/iannil/huan/internal/config"
	"github.com/iannil/huan/internal/daemon/eventbus"
	"github.com/iannil/huan/internal/dev"
	"github.com/iannil/huan/internal/plugin"
	"github.com/iannil/huan/internal/theme"
	"github.com/spf13/cobra"
)

var devCmd = &cobra.Command{
	Use:   "dev",
	Short: "Start the development server",
	Long:  "Start the development server with LiveReload, file watching, and admin panel.",
	RunE:  runDev,
}

func init() {
	rootCmd.AddCommand(devCmd)
	devCmd.Flags().String("port", "1313", "port to serve on")
	devCmd.Flags().String("bind", "127.0.0.1", "interface to bind")
	devCmd.Flags().BoolP("buildDrafts", "D", false, "include draft content")
	devCmd.Flags().Bool("disableLiveReload", false, "disable browser auto-refresh")
	devCmd.Flags().Duration("debounce", 400*time.Millisecond, "file change debounce delay")
	devCmd.Flags().Bool("timings", false, "report build stage durations")
	devCmd.Flags().Bool("disableWatch", false, "do not watch files for changes")
	devCmd.Flags().String("adminDev", "", "admin UI Vite dev server URL (e.g. http://localhost:5173) for hot reload")
	devCmd.Flags().String("plugins", "", "path to plugins directory (overrides sourceDir/plugins/)")
}

func runDev(cmd *cobra.Command, args []string) (devErr error) {
	port, _ := cmd.Flags().GetString("port")
	bind, _ := cmd.Flags().GetString("bind")
	disableLR, _ := cmd.Flags().GetBool("disableLiveReload")
	disableWatch, _ := cmd.Flags().GetBool("disableWatch")
	debounce, _ := cmd.Flags().GetDuration("debounce")
	includeDrafts, _ := cmd.Flags().GetBool("buildDrafts")
	adminDevURL, _ := cmd.Flags().GetString("adminDev")
	pluginsDir, _ := cmd.Flags().GetString("plugins")

	startupTimings := commandTimings(cmd)
	startupStart := time.Now()
	startupReported := false
	var startupErr error
	defer func() {
		if !startupReported {
			reportTimings(cmd, startupTimings, "build total", startupStart, devErr)
		}
	}()
	var cfg *config.Config
	err := startupTimings.Measure("cli", "config preparation", func() error { var err error; cfg, err = config.Load(sourceDir); return err })
	if err != nil {
		startupErr = err
		return fmt.Errorf("load config: %w", err)
	}

	token, tokenFromEnv := admin.ResolveToken()
	if err := admin.CheckBindSafety(bind, token); err != nil {
		return err
	}
	if !tokenFromEnv {
		var err error
		if token, err = admin.GenerateToken(); err != nil {
			return fmt.Errorf("generate admin token: %w", err)
		}
		admin.MustPrintAutoGeneratedToken(token, true)
	}

	browserHost := bind
	if bind == "0.0.0.0" || bind == "::" {
		browserHost = "localhost"
	}

	devBaseURL := "http://" + browserHost + ":" + port + "/"
	lrURL := ""
	injectLR := false
	if !disableLR {
		injectLR = true
		lrURL = "ws://" + browserHost + ":" + port + "/livereload"
	}

	var hub *dev.LiveReloadHub
	if !disableLR {
		hub = dev.NewHub()
	}

	tmpDir, err := os.MkdirTemp("", "huan-dev-*")
	if err != nil {
		return fmt.Errorf("mkdtemp: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	buildOpts := build.Options{
		Timings:          startupTimings,
		SourceDir:        sourceDir,
		OutputDir:        tmpDir,
		IncludeDrafts:    includeDrafts,
		InjectLiveReload: injectLR,
		LiveReloadURL:    lrURL,
		BaseURLOverride:  devBaseURL,
		Logf:             func(format string, a ...any) { fmt.Printf(format, a...) },
	}

	// Create PluginRegistry and ThemeManager, auto-activate from config
	var reg *plugin.Registry
	var themeMgr *theme.Manager
	_ = startupTimings.Measure("cli", "registry + theme preparation", func() error {
		reg, _ = newPluginRegistry(cfg, sourceDir, pluginsDir)
		buildOpts.PluginRegistry = reg
		themeMgr = theme.NewManager(reg)
		if cfg.Theme != "" {
			if err := themeMgr.Activate(cfg.Theme); err != nil {
				fmt.Fprintf(cmd.ErrOrStderr(), "huan: theme activate %q: %v\n", cfg.Theme, err)
			}
		}
		buildOpts.ThemeManager = themeMgr
		return nil
	})

	runBuild := func(opts build.Options) error {
		if cfg.IsMultiLanguage() {
			res, err := build.BuildMultiSite(opts)
			if err != nil {
				return err
			}
			fmt.Println(build.SummarizeMultiSite(res))
		} else {
			_, err := build.BuildSite(opts)
			if err != nil {
				return err
			}
		}
		// Run image pipeline after build if configured
		var reg *plugin.Registry
		_ = opts.Timings.Measure("cli", "image registry preparation", func() error { reg, _ = newPluginRegistry(cfg, sourceDir, pluginsDir); return nil })
		if err := opts.Timings.Measure("cli", "image processing", func() error { return runImagePipeline(sourceDir, opts.OutputDir, reg) }); err != nil {
			return fmt.Errorf("image pipeline: %w", err)
		}
		return nil
	}

	startupErr = runBuild(buildOpts)
	reportTimings(cmd, startupTimings, "build total", startupStart, startupErr)
	startupReported = true
	if startupErr != nil {
		return startupErr
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	var (
		rebuildBusy   atomic.Bool
		rebuildPended atomic.Bool
	)
	nextDir := tmpDir + ".next"
	doRebuild := func() {
		if !rebuildBusy.CompareAndSwap(false, true) {
			rebuildPended.Store(true)
			return
		}
		for {
			fmt.Println("[watch] change detected, rebuilding...")
			start := time.Now()
			_ = os.RemoveAll(nextDir)
			buildOpts.OutputDir = nextDir
			buildOpts.Timings = commandTimings(cmd)
			var swapErr error
			rebuildErr := func() (err error) {
				defer func() { reportTimings(cmd, buildOpts.Timings, "rebuild total", start, err) }()
				if err = runBuild(buildOpts); err != nil {
					return err
				}
				swapErr = buildOpts.Timings.Measure("cli", "directory swap", func() error { return build.SwapBuildDir(tmpDir, nextDir) })
				return swapErr
			}()
			if err := rebuildErr; err != nil && swapErr == nil {
				_ = os.RemoveAll(nextDir)
				buildOpts.OutputDir = tmpDir
				fmt.Printf("[watch] rebuild error: %v\n", err)
				if hub != nil {
					hub.BroadcastAlert(fmt.Sprintf("huan rebuild error: %v", err))
				}
				break
			}
			if swapErr != nil {
				_ = os.RemoveAll(nextDir)
				buildOpts.OutputDir = tmpDir
				fmt.Printf("[watch] swap failed, kept old build: %v\n", swapErr)
			}
			buildOpts.OutputDir = tmpDir
			fmt.Printf("[watch] rebuild complete in %v\n", time.Since(start))
			if hub != nil {
				hub.BroadcastReload()
			}
			if !rebuildPended.CompareAndSwap(true, false) {
				break
			}
		}
		rebuildBusy.Store(false)
	}

	if !disableWatch {
		watcherOpts := dev.WatcherOptions{
			SourceDir: sourceDir,
			Debounce:  debounce,
			OnChange:  doRebuild,
			Logf:      func(format string, a ...any) { fmt.Printf(format, a...) },
		}
		// The publish dir is build output, not input: a concurrent
		// `huan build` / deploy rewriting it must not loop dev rebuilds.
		if dir := filepath.Clean(cfg.PublishDir); dir != "" && dir != "." && !filepath.IsAbs(dir) {
			watcherOpts.IgnoreDirs = []string{dir}
		}
		watcher, err := dev.NewWatcher(watcherOpts)
		if err != nil {
			fmt.Printf("WARNING: file watcher unavailable: %v\n", err)
			fmt.Println("WARNING: use --disableWatch to suppress this message")
		} else {
			go watcher.Run(ctx)
		}
	}

	fmt.Println("Press Ctrl+C to stop")

	serveURL := fmt.Sprintf("http://%s:%s/", browserHost, port)
	// Plugin lifecycle manager for the admin API (list/load/unload/reload),
	// sharing the build registry and watching the same plugin dir. Needs a
	// real (non-nil) bus: LifecycleManager.Publish calls bus.Publish
	// unconditionally on load/unload/reload events.
	pluginLoader := plugin.NewLoader(pluginDirFromSource(sourceDir))
	if pluginsDir != "" {
		pluginLoader = plugin.NewLoader(pluginsDir)
	}
	adminPluginMgr := plugin.NewLifecycleManager(reg, pluginLoader, eventbus.NewChannelBus())
	adminHandler := admin.NewHandler(admin.HandlerOptions{
		Cfg:           cfg,
		SourceDir:     sourceDir,
		Rebuild:       doRebuild,
		ServeURL:      serveURL,
		BindAddr:      bind,
		Token:         token,
		MemoryDir:     filepath.Join(sourceDir, "memory", "daily"),
		PluginManager: adminPluginMgr,
		ThemeManager:  themeMgr,
	})
	if adminDevURL != "" {
		fmt.Printf("Admin UI dev mode: proxying to %s\n", adminDevURL)
		adminHandler = dev.NewAdminDevProxy(adminDevURL, adminHandler)
	}

	srv := dev.New(dev.ServerOptions{
		OutputDir:    tmpDir,
		Bind:         bind,
		Port:         port,
		Hub:          hub,
		AdminHandler: adminHandler,
		Logf:         func(format string, a ...any) { fmt.Printf(format, a...) },
	})
	return srv.Run(ctx)
}
